# Generated by Django 4.1.6 on 2023-02-07 23:15

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='first_symbol can`t be a special symbol', regex=re.compile('^\\w.{0,}$'))])),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('important', 'important'), ('medium', 'medium'), ('small', 'small')], max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('execution_status', models.CharField(choices=[('completed', 'completed'), ('in_process', 'in_process')], default='in_process', max_length=20)),
            ],
        ),
    ]
