# Generated by Django 4.1.6 on 2023-02-07 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buyer_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
