# Generated by Django 4.1.6 on 2023-02-08 10:32

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='first symbol can`t be a special symbol', regex=re.compile('^\\w.{0,}$'))]),
        ),
    ]
