# Generated by Django 4.1.6 on 2023-02-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_item_buyer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='buyer_id',
            new_name='buyer',
        ),
    ]
