# Generated by Django 4.1.6 on 2023-02-07 17:58

from django.db import migrations, models
import test_api.my_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_rename_buyer_id_item_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[test_api.my_api.models.validate_first_char])),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('imp', 'important'), ('med', 'medium'), ('sml', 'small')], max_length=3)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('execution_status', models.CharField(choices=[('compl', 'completed'), ('in_pr', 'in_process')], default='in_pr', max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
